Repository UDT-Uplus-Dream-Team/UDT-fe, pull requests merged in 2025-08, with the labels that each got.

#88 [UDT-186] 피드백 삭제 엔드포인트 변경으로 인한 삭제 api 수정
  src/app/profile/feedbacks/page.tsx
  src/app/profile/recommend/page.tsx
  src/hooks/profile/useDeleteFeedback.ts
  src/hooks/profile/useDeleteToast.ts
  src/lib/apis/profile/feedbackService.ts
  src/lib/apis/profile/recommendService.ts
Labels: bug

#86 [UDT-191] 탐색(Explore) 페이지 QA 사항 2차 수정
  src/app/explore/page.tsx
  src/components/explore/ExplorePageCarousel.tsx
  src/components/explore/FilterRadioButtonGroup.tsx
  src/components/explore/PosterCardsGrid.tsx
Labels: bug

#87 [UDT-208] 온보딩 query param 수정
  src/app/layout-wrapper.tsx
  src/app/onboarding/OnboardingClient.tsx
  src/app/onboarding/page.tsx
Labels: enhancement

#89 [UDT-210] 관리자(백오피스) 페이지 최상단 page.tsx 수정 및 사이드 바, 요청 대기열 페이지 수정 + 일부 QA 사항 수정
  package-lock.json
  package.json
  src/app/admin/page.tsx
  src/app/explore/page.tsx
  src/components/admin/RequestQueueDashboard.tsx
  src/components/admin/SmoothExpandableSidebar.tsx
  src/components/explore/ExplorePageCarousel.tsx
  src/components/explore/FilterRadioButtonGroup.tsx
  src/components/explore/PosterCardScrollBox.tsx
  src/components/explore/PosterCardsGrid.tsx
  src/components/explore/RepresentativeContentCard.tsx
  src/components/ui/dropdown-menu.tsx
  src/components/ui/table.tsx
Labels: enhancement

#90 [UDT-192] 설문조사 쿼리 파라미터로 변경
  src/app/survey/SurveyFlow.tsx
  src/app/survey/page.tsx
  src/components/admin/ContentForm.tsx
Labels: enhancement

#94 [UDT-225] 감독, 출연진 검색 및 등록 다이얼로그 추가
  src/components/admin/ContentCard.tsx
  src/components/admin/ContentForm.tsx
  src/components/admin/dialogs/actorSearchDialog.tsx
  src/components/admin/dialogs/directorSearchDialog.tsx
  src/hooks/admin/useDeleteContent.ts
  src/hooks/admin/useGetCastsSearch.ts
  src/hooks/admin/useGetContentList.ts
  src/hooks/admin/useGetDirectorsSearch.ts
  src/hooks/admin/usePostCasts.ts
  src/hooks/admin/usePostDirectors.ts
  src/hooks/admin/usePostUploadImages.ts
  src/lib/apis/admin/getCastsSearch.ts
  src/lib/apis/admin/getDirectorsSearch.ts
  src/lib/apis/admin/postCasts.ts
  src/lib/apis/admin/postDirectors.ts
  src/lib/apis/admin/postUploadImages.ts
  src/types/admin/Cast.ts
  src/types/admin/Director.ts
Labels: enhancement

#96 [UDT-220] 탐색 페이지 플랫폼별 인기 콘텐츠 조회 API 연동
  src/app/explore/page.tsx
  src/components/explore/PosterCard.tsx
  src/components/explore/PosterCardScrollBox.tsx
  src/components/explore/PosterCardsGrid.tsx
  src/hooks/explore/useGetContentDetails.ts
  src/hooks/explore/useGetContentListByBoxType.ts
  src/hooks/explore/useGetPlatformPicksContents.ts
  src/lib/apis/explore/getPlatformPicksContents.ts
Labels: enhancement

#99 [UDT-232] 온보딩 페이지 관련 플로우 수정
  src/app/onboarding/OnboardingClient.tsx
  src/app/onboarding/Step3.tsx
  src/app/onboarding/Step4.tsx
  src/app/onboarding/Step5.tsx
  src/app/onboarding/Step6.tsx
  src/app/onboarding/Step7.tsx
  src/app/onboarding/Step8.tsx
  src/app/onboarding/moviedata.ts
  src/app/recommend/StartScreen.tsx
  src/app/survey/SurveyFlow.tsx
  src/stories/Toast/Toast.stories.tsx
Labels: bug, enhancement

#102 [UDT-241] 탐색 페이지에서 가로 스크롤 방지 및 PosterCard에서 <Image> 컴포넌트에 대해 onLoad property로 변경
  src/app/explore/page.tsx
  src/components/explore/PosterCard.tsx
Labels: bug

#103 [UDT-242] hotfix: 온보딩 파트 버그 수정
  src/app/onboarding/Step0.tsx
  src/app/onboarding/Step1.tsx
  src/app/onboarding/Step2.tsx
  src/app/onboarding/Step3.tsx
  src/app/onboarding/Step4.tsx
  src/app/onboarding/Step5.tsx
  src/app/onboarding/Step6.tsx
  src/app/onboarding/Step8.tsx
  src/app/onboarding/page.tsx
  src/app/recommend/FinishScreen.tsx
  src/app/recommend/RecommendScreen.tsx
  src/app/recommend/ResultScreen.tsx
  src/app/survey/SurveyFlow.tsx
  src/app/survey/page.tsx
  src/components/common/LoadingScreen.tsx
Labels: bug

#91 [UDT-211] 백오피스 페이지에서 "배치 대기열" 및 "배치 결과"를 확인할 수 있는 페이지 UI 구현
  public/icons/firefly-adminpage-logo.png
  src/app/admin/page.tsx
  src/app/layout.tsx
  src/components/admin/BatchChartCardSectionBody.tsx
  src/components/admin/BatchJobDetailDialog.tsx
  src/components/admin/BatchRequestQueueDashboard.tsx
  src/components/admin/BatchRequestQueueTable.tsx
  src/components/admin/BatchRequestQueueTopCardSection.tsx
  src/components/admin/BatchResultDashboard.tsx
  src/components/admin/BatchResultDashboardTable.tsx
  src/components/admin/BatchResultTopCardSection.tsx
  src/components/admin/FailedJobsTable.tsx
  src/components/admin/InvalidJobsTable.tsx
  src/components/admin/JobTypeDropDown.tsx
  src/components/admin/RequestQueueDashboard.tsx
  src/components/admin/SmoothExpandableSidebar.tsx
  src/hooks/admin/useDeleteInvalidJobs.ts
  src/hooks/admin/useGetBatchJobList.ts
  src/hooks/admin/useGetBatchRequestQueueStatistics.ts
  src/hooks/admin/useGetBatchResultStatistics.ts
  src/hooks/admin/useGetBatchResults.ts
  src/hooks/admin/useGetJobDetail.ts
  src/hooks/admin/usePostRetryFailedJobs.ts
  src/lib/apis/admin/batch/deleteInvalidJobs.ts
  src/lib/apis/admin/batch/getBatchJobList.ts
  src/lib/apis/admin/batch/getBatchRequestQueueStatistics.ts
  src/lib/apis/admin/batch/getBatchResultStatistics.ts
  src/lib/apis/admin/batch/getBatchResults.ts
  src/lib/apis/admin/batch/getJobDetail.ts
  src/lib/apis/admin/batch/postRetryFailedJobs.ts
  src/types/admin/batch.ts
  src/utils/getRequestTypeConfigInBatchResult.ts
Labels: enhancement

#98 [UDT-229] 관리자 페이지 콘텐츠 관리 중 인물 등록 탭 구현
  src/components/admin/ContentDetail.tsx
  src/components/admin/ContentForm.tsx
  src/components/admin/ContentFormSections/BasicInfo.tsx
  src/components/admin/ContentFormSections/CastInfo.tsx
  src/components/admin/ContentFormSections/DetailedInfo.tsx
  src/components/admin/ContentFormSections/DirectorInfo.tsx
  src/components/admin/ContentFormSections/PlatformInfo.tsx
  src/components/admin/bulkPersonRegistration.tsx
  src/components/admin/dialogs/actorSearchDialog.tsx
  src/components/admin/dialogs/directorSearchDialog.tsx
  src/components/common/Toast.tsx
  src/hooks/admin/usePostCasts.ts
  src/hooks/admin/usePostDirectors.ts
  src/hooks/admin/usePostUploadImages.ts
Labels: enhancement
