Repository UDT-Uplus-Dream-Team/UDT-fe, pull requests merged in 2025-07, with the labels that each got.

#5 [UDT-43] feat: CircleOption 컴포넌트 제작
  package-lock.json
  package.json
  public/images/ott/appleTv.png
  public/images/ott/coupangPlay.png
  public/images/ott/disneyPlus.png
  public/images/ott/neflix.png
  public/images/ott/tving.png
  public/images/ott/watcha.png
  public/images/ott/wavve.png
  src/components/common/circleOption.tsx
  src/components/ui/avatar.tsx
Labels: enhancement

#9 [UDT-49] feat: 설문조사 UI 제작
  public/icons/check.svg
  public/images/genre/action.png
  public/images/genre/adult.png
  public/images/genre/adventure.png
  public/images/genre/animation.png
  public/images/genre/comedy.png
  public/images/genre/crime.png
  public/images/genre/documentary.png
  public/images/genre/drama.png
  public/images/genre/fantasy.png
  public/images/genre/historical-drama.png
  public/images/genre/horror.png
  public/images/genre/kids.png
  public/images/genre/martial-arts.png
  public/images/genre/musical.png
  public/images/genre/mystery.png
  public/images/genre/reality.png
  public/images/genre/romance.png
  public/images/genre/sf.png
  public/images/genre/stand-up-comedy.png
  public/images/genre/survival.png
  public/images/genre/talk-show.png
  public/images/genre/thriller.png
  public/images/genre/variety.png
  public/images/genre/western.png
  public/images/ott/netflix.png
  src/app/survey/page.tsx
  src/components/common/circleOption.tsx
  src/components/survey/Step1.tsx
  src/components/survey/Step2.tsx
  src/components/survey/Step3.tsx
  src/components/survey/SurveyComplete.tsx
  src/components/survey/SurveyPosterCard.tsx
  src/contexts/SurveyContext.tsx
  src/hooks/useSurveyContext.ts
  src/lib/genres.ts
  src/lib/platforms.ts
  src/stories/Survey/SurveyPosterCard.stories.tsx
  src/stories/common/CircleOption.stories.tsx
  src/types/Genre.ts
  src/types/Platform.ts
  src/types/SurveyContext.ts
  tsconfig.json
Labels: enhancement

#15 hotfix: survey에서 import 수정된 경로로 변경
  src/app/survey/page.tsx
  src/components/survey/Step1.tsx
  src/components/survey/Step2.tsx
  src/components/survey/Step3.tsx
Labels: bug

#17 [UDT-75] 추천 페이지 및 엄선된 콘텐츠 페이지 연결 및 개선
  package-lock.json
  src/app/layout.tsx
  src/app/recommendation/page.tsx
  src/app/recommendation/result/page.tsx
  src/components/Ticket/Ticket.tsx
  src/components/common/bottom-navbar.tsx
Labels: enhancement

#16 [UDT-57] 탐색 페이지 메인 화면 마크업
  .storybook/main.ts
  package-lock.json
  package.json
  public/disney-plus-icon.jpg
  public/images/mockdata/choonsik.webp
  public/images/mockdata/hops.webp
  public/images/mockdata/judy.webp
  public/images/mockdata/nick.jpeg
  public/images/mockdata/zootopia.jpg
  public/logos/appletv.png
  public/logos/coupangplay.png
  public/logos/disney.jpg
  public/logos/netflix.jpg
  public/logos/tving.jpg
  public/logos/watcha.png
  public/logos/wave.jpg
  src/app/explore/page.tsx
  src/app/globals.css
  src/app/layout.tsx
  src/app/recommendation/moviedata.ts
  src/components/Ticket/Ticket.tsx
  src/components/common/bottom-navbar.tsx
  src/components/explore/DetailBottomSheetContent.tsx
  src/components/explore/ExplorePageCarousel.tsx
  src/components/explore/FilterBottomSheetContent.tsx
  src/components/explore/FilterRadioButton.tsx
  src/components/explore/FilterRadioButtonGroup.tsx
  src/components/explore/OttCircleOption.tsx
  src/components/explore/PlatformButton.tsx
  src/components/explore/PosterCard.tsx
  src/components/explore/PosterCardScrollBox.tsx
  src/components/explore/RepresentativeContentCard.tsx
  src/constants/FilterData.ts
  src/contexts/SurveyContext.tsx
  src/hooks/useContentData.ts
  src/hooks/useExplorePageState.ts
  src/hooks/useFetchOttFilterOptions.ts
  src/hooks/useGetContentDetail.ts
  src/lib/apis/explore.ts
  src/lib/apis/getContentDetail.ts
  src/lib/apis/movieService.ts
  src/lib/filterData.ts
  src/lib/getPlatformLogo.ts
  src/store/ExplorePageContext.tsx
  src/stories/Explore/FilterRadioButton.stories.ts
  src/stories/Explore/OttCircleOption.stories.ts
  src/stories/Explore/PosterCard.stories.ts
  src/stories/Explore/RepresentativeContentCard.stories.ts
  src/stories/Ticket/Ticket.stories.ts
  src/stories/mypage/PlatformButton.stories.ts
  src/types/ExplorePageContextType.ts
  src/types/FilterRadioButtonProps.ts
  src/types/Moviedata.ts
  src/types/PosterCardProps.ts
  src/types/UserInfo.ts
  src/types/explore/ContentDetail.ts
  src/types/explore/Explore.ts
  src/utils/getPlatformLogo.ts
  tsconfig.json
Labels: enhancement

#21 [UDT-83] feat: 카카오 소셜 로그인 연동
  public/icons/FireFlyLogo.png
  public/icons/edit-icon.svg
  public/icons/kakaologin-icon.png
  public/icons/logout-icon.svg
  src/app/auth/callback/page.tsx
  src/app/globals.css
  src/app/page.tsx
  src/app/profile/page.tsx
  src/components/profile/SubscriptionBox.tsx
  src/hooks/useFetchOttFilterOptions.ts
  src/hooks/useGetUserProfile.ts
  src/lib/apis/authService.ts
  src/lib/apis/axiosInstance.ts
  src/types/auth/UserProfile.ts
Labels: enhancement

#25 [UDT-87] 탐색(explore) 페이지 UI/UX 개선 작업 및 API 연동 준비, 기타 오류 해결
  package-lock.json
  public/images/mockdata/haul-backdrop.jpeg
  public/images/mockdata/hime-backdrop.jpg
  public/images/mockdata/insideout-backdrop.webp
  public/images/mockdata/kiki-backdrop.webp
  public/images/mockdata/nausika-backdrop.webp
  public/images/mockdata/placeholder.jpg
  public/images/mockdata/sen-backdrop.webp
  public/images/mockdata/tazza-backdrop.webp
  public/images/mockdata/tazza1-poster.webp
  public/images/mockdata/totoro-backdrop.webp
  public/images/poster5.webp
  src/app/explore/page.tsx
  src/app/layout-wrapper.tsx
  src/app/layout.tsx
  src/app/page.tsx
  src/app/profile/page.tsx
  src/app/recommend/ResultScreen.tsx
  src/app/recommend/StartScreen.tsx
  src/components/explore/DetailBottomSheetContent.tsx
  src/components/explore/ExplorePageCarousel.tsx
  src/components/explore/PosterCard.tsx
  src/components/explore/PosterCardScrollBox.tsx
  src/components/explore/PosterCardsGrid.tsx
  src/components/explore/RepresentativeContentCard.tsx
  src/components/explore/VideoPlayer.tsx
  src/hooks/explore/useFetchOttFilterOptions.ts
  src/hooks/explore/useGetFilteredContents.ts
  src/hooks/useContentData.ts
  src/hooks/useExplorePageState.ts
  src/hooks/useGetFilteredContent.ts
  src/hooks/useGetUserProfile.ts
  src/lib/apis/explore/getFilteredContents.ts
  src/lib/apis/explore/getLatestContents.ts
  src/lib/apis/getFilteredContent.ts
  src/types/explore/Explore.ts
  src/types/explore/FilteredContent.ts
  src/utils/createFilterRequestParam.ts
  src/utils/getMockContentData.ts
  src/utils/getYouTubeEmbedUrl.ts
Labels: enhancement

#26 [UDT-88] 추천 페이지 API 연동 세팅 및 전역 상태 세팅
  public/icons/FireFlyLogo.png
  src/app/page.tsx
  src/app/recommend/ContentList.ts
  src/app/recommend/RecommendContent.ts
  src/app/recommend/RecommendScreen.tsx
  src/app/recommend/ResultScreen.tsx
  src/app/recommend/StartScreen.tsx
  src/app/recommend/page.tsx
  src/components/common/Toast.tsx
  src/lib/apis/recommend/getCuratedContents.ts
  src/lib/apis/recommend/getRecommendationContents.ts
  src/lib/apis/recommend/postFeedbackContent.ts
  src/store/useRecommendStore.ts
Labels: enhancement

#28 hotfix: ReadMe survey, backoffice 수정
  README.md
Labels: documentation

#35 [UDT-92] 프로필 페이지 API 연동
  package.json
  src/app/layout-wrapper.tsx
  src/app/onboarding/Step6.tsx
  src/app/onboarding/Step7.tsx
  src/app/onboarding/Step8.tsx
  src/app/onboarding/onBordingStart.tsx
  src/app/profile/edit/page.tsx
  src/app/profile/feedbacks/feedbacks.ts
  src/app/profile/feedbacks/page.tsx
  src/app/profile/page.tsx
  src/app/profile/profileData.ts
  src/app/profile/recommend/page.tsx
  src/app/profile/recommend/recommend.ts
  src/components/common/Toast.tsx
  src/components/explore/PlatformButton.tsx
  src/components/profile/PlatformButton.tsx
  src/components/profile/RecommendationCard.tsx
  src/components/profile/SubscriptionBox.tsx
  src/components/ui/skeleton.tsx
  src/hooks/profile/useDeleteFeedback.ts
  src/hooks/profile/useGetCuratedContents.ts
  src/hooks/profile/useGetUserInfo.ts
  src/hooks/profile/useInfiniteFeedbacks.ts
  src/hooks/profile/usePatchGenre.ts
  src/hooks/profile/usePatchPlatform.ts
  src/hooks/profile/usePreferenceHandler.ts
  src/hooks/useDeleteMode.ts
  src/hooks/usePosterModal.ts
  src/lib/apis/authService.ts
  src/lib/apis/profile/feedbackService.ts
  src/lib/apis/profile/recommendService.ts
  src/lib/apis/profile/surveyService.ts
  src/lib/apis/profile/userService.ts
  src/stories/mypage/MovieCard.stories.ts
  src/types/UserInfo.ts
  src/types/profile/Mypage.ts
  src/types/profile/RecommendedContent.ts
Labels: enhancement

#38 hotfix: fixing error for ci/cd build
  src/components/explore/ExplorePageCarousel.tsx
  src/components/explore/PlatformButton.tsx
  src/components/explore/PosterCard.tsx
  src/components/profile/PlatformButton.tsx
  src/lib/apis/explore.ts
  src/lib/apis/movieService.ts
  src/stories/Explore/RepresentativeContentCard.stories.ts
  src/types/profile/Mypage.ts
Labels: bug

#32 [UDT-97] 추천 페이지 API 연동 방식 변경에 따른 상태 관리 변경
  next.config.ts
  src/app/recommend/FinishScreen.tsx
  src/app/recommend/LoadingScreen.tsx
  src/app/recommend/RecommendScreen.tsx
  src/app/recommend/ResultScreen.tsx
  src/app/recommend/StartScreen.tsx
  src/lib/apis/recommend/getCuratedContents.ts
  src/lib/apis/recommend/postFeedbackContent.ts
  src/store/useRecommendStore.ts
Labels: enhancement

#39 [UDT-109] API 응답을 화면에 표시하기 위한 type 수정 및 기본 poster, backdrop 이미지 추가
  next.config.ts
  package-lock.json
  package.json
  public/images/default-backdrop.png
  public/images/default-poster.png
  src/components/explore/DetailBottomSheetContent.tsx
  src/components/explore/PosterCard.tsx
  src/components/explore/VideoPlayer.tsx
  src/hooks/explore/useGetFilteredContents.ts
  src/lib/apis/explore/getFilteredContents.ts
  src/types/explore/FilteredContent.ts
  src/utils/createFilterRequestParam.ts
Labels: bug

#43 [UDT-108] 콘텐츠 목록 무한 스크롤 적용 및 등록 모달 구조 변경
  src/app/survey/page.tsx
  src/components/admin/AdminDashboard.tsx
  src/components/admin/contentCard.tsx
  src/components/admin/contentDetail.tsx
  src/components/admin/contentForm.tsx
  src/components/admin/searchFilter.tsx
  src/constants/index.ts
  src/hooks/admin/useDeleteContent.ts
  src/hooks/admin/useGetContentList.ts
  src/hooks/admin/usePatchContent.ts
  src/hooks/admin/usePostContent.ts
  src/hooks/survey/usePostSurvey.ts
  src/lib/apis/admin/getContentList.ts
  src/lib/apis/survey/postSurvey.ts
  src/types/admin/Content.ts
  src/types/survey/Survey.ts
  src/utils/getContentUtils.ts
Labels: enhancement

#40 [UDT-103] 피드백 및 엄선된 페이지 api 연동
  src/app/profile/edit/page.tsx
  src/app/profile/feedbacks/feedbacks.ts
  src/app/profile/feedbacks/page.tsx
  src/app/profile/page.tsx
  src/app/profile/recommend/page.tsx
  src/app/profile/recommend/recommend.ts
  src/components/profile/MovieCard.tsx
  src/components/profile/MovieDetailModal.tsx
  src/components/profile/RecommendationCard.tsx
  src/hooks/profile/useDeleteCurated.ts
  src/hooks/profile/useDeleteFeedback.ts
  src/hooks/profile/useDeleteFeedbackToast.ts
  src/hooks/profile/useDeleteMode.ts
  src/hooks/profile/useGetCuratedContents.ts
  src/hooks/profile/useGetStoredContentDetail.ts
  src/hooks/profile/useInfiniteCuratedContents.ts
  src/hooks/profile/useInfiniteFeedbacks.ts
  src/hooks/profile/useLogoutHandler.ts
  src/hooks/profile/usePreferenceHandler.ts
  src/hooks/useDeleteMode.ts
  src/hooks/usePosterModal.ts
  src/lib/apis/profile/feedbackService.ts
  src/lib/apis/profile/getStoredContentDetail.ts
  src/lib/apis/profile/recommendService.ts
  src/types/profile/FeedbackContent.ts
  src/types/profile/RecommendedContent.ts
  src/types/profile/StoredContentDetail.ts
Labels: enhancement

#41 [UDT-112] 탐색 페이지에서의 API 응답을 화면에 자연스럽게 표시하기 위한 리팩토링 진행
  .coderabbit.yaml
  src/components/common/Skeleton.tsx
  src/components/explore/DetailBottomSheetContent.tsx
  src/components/explore/ExplorePageCarousel.tsx
  src/components/explore/ExplorePageCarouselSkeleton.tsx
  src/components/explore/PosterCard.tsx
  src/components/explore/PosterCardScrollBox.tsx
  src/components/explore/PosterScrollBoxSkeleton.tsx
  src/hooks/explore/useGetContentDetails.ts
  src/hooks/explore/useGetContentListByBoxType.ts
  src/hooks/explore/useGetLatestContents.ts
  src/hooks/explore/useGetPopularContents.ts
  src/hooks/explore/useGetTodayRecommendContents.ts
  src/lib/apis/explore/getContentDetails.ts
  src/lib/apis/explore/getLatestContents.ts
  src/lib/apis/explore/getPopularContents.ts
  src/lib/apis/explore/getTodayContents.ts
  src/types/explore/Explore.ts
  src/utils/checkImgSrcValidity.ts
Labels: enhancement

#48 [UDT-122] 마이페이지 엄선된 컨텐츠 삭제 api 연동
  src/app/profile/feedbacks/page.tsx
  src/app/profile/recommend/page.tsx
  src/components/Ticket/Ticket.tsx
  src/components/common/Toast.tsx
  src/hooks/profile/useDeleteMode.ts
  src/hooks/profile/useDeleteToast.ts
  src/hooks/profile/usePreferenceHandler.ts
  src/lib/apis/profile/recommendService.ts
Labels: enhancement

#51 [UDT-137] sonner 라이브러리를 통해 구현한 toast의 화면 정렬 문제 수정
  src/app/layout.tsx
  src/components/common/Toast.tsx
  src/hooks/profile/useDeleteToast.ts
Labels: bug

#54 [UDT-130] Ticket 컴포넌트 반응형 디자인 수정, 모바일/개발자 도구 애니메이션 수정, 스와이프 및 로딩 수정
  src/app/recommend/LoadingScreen.tsx
  src/app/recommend/RecommendScreen.tsx
  src/app/recommend/ResultScreen.tsx
  src/app/recommend/StartScreen.tsx
  src/components/Ticket/Ticket.tsx
  src/components/common/sparkle_background.tsx
  src/hooks/recommend/usePostCuratedContents.ts
Labels: enhancement

#56 hotfix: Explore 화면에서 스크롤 문제 해결
  src/components/explore/ExplorePageCarousel.tsx
  src/components/explore/FilterRadioButtonGroup.tsx
  src/components/explore/PosterCard.tsx
  src/components/explore/PosterCardScrollBox.tsx
  src/components/explore/PosterCardsGrid.tsx
  src/components/explore/RepresentativeContentCard.tsx
  src/constants/FilterData.ts
  src/utils/getErrorMessage.ts
Labels: bug

#58 hotfix: 설문조사(survey) 페이지 데이터 타입 및 종료 시점 일시 변경
  src/app/survey/page.tsx
  src/lib/platforms.ts
  src/types/survey/Survey.ts
Labels: bug

#59 hotfix: 탐색 페이지에서 발생하는 API 통신 오류 및 웹사이트 기본 정보 수정
  next.config.ts
  public/images/default-profile.avif
  public/vercel.svg
  src/app/favicon.ico
  src/app/layout.tsx
  src/app/profile/page.tsx
  src/components/explore/DetailBottomSheetContent.tsx
  src/components/explore/VideoPlayer.tsx
  src/types/explore/Explore.ts
  src/utils/createFilterRequestParam.ts
  src/utils/formattingOpenDate.ts
Labels: bug

#60 hotfix: 설문조사 step3 추가, toast 글씨 보이게 수정, ott 1개 이상으로 제한
  src/app/survey/page.tsx
  src/components/survey/Step1.tsx
  src/components/survey/Step3.tsx
  src/components/survey/SurveyPosterCard.tsx
  src/components/survey/mockContents.ts
Labels: bug

#62 hotfix: 설문조사 step3에서 콘텐츠 목록 안보이는 문제 해결
  src/app/globals.css
  src/components/survey/Step2.tsx
  src/components/survey/Step3.tsx
  src/components/survey/SurveyPosterCard.tsx
  src/components/survey/mockContents.ts
Labels: bug

#61 Hotfix/recommend screen fix
  next.config.ts
  src/app/recommend/RecommendScreen.tsx
  src/components/Ticket/Ticket.tsx
  src/components/profile/MovieCard.tsx
Labels: bug

#64 Hotfix: 설문조사 에러 토스트 중복 방지 훅 적용 및 step3 콘텐츠 목록 단계 비활성화로 변경
  src/app/survey/page.tsx
  src/components/survey/Step1.tsx
  src/components/survey/Step2.tsx
  src/components/survey/mockContents.ts
  src/hooks/useErrorToastOnce.ts
Labels: bug

#72 hotfix: global.css에서 md 사이즈 수정
  src/app/globals.css
Labels: bug

#73 hotfix: main 브랜치 hotfix 사항 dev에 적용
  src/app/globals.css
  src/app/page.tsx
  src/middleware.ts
Labels: bug, enhancement

#79 hotfix: layout 버그 수정 및 DetailBottomSheetContent 스켈레톤 추가
  src/app/explore/page.tsx
  src/app/profile/feedbacks/page.tsx
  src/app/profile/recommend/page.tsx
  src/components/common/bottom-navbar.tsx
  src/components/explore/DetailBottomSheetContent.tsx
  src/components/explore/DetailBottomSheetSkeleton.tsx
Labels: bug, enhancement

#78 Hotfix: 마이페이지 상세보기 카드 모바일 화면에 맞게 수정
  src/components/profile/MovieCard.tsx
  src/components/profile/MovieDetailModal.tsx
Labels: bug, enhancement
